### ISSUE TITLE
Failed to enable SSP

### ISSUE THREAD

**Issue by spideyshanexample** [pentestfunctions/BlueDucky#23]
2024-04-01 22:10:27,385 - ERROR - Failed to enable SSP: Can't set Simple Pairing mode on hci0: Input/output error (5)                                     
                                                                             
2024-04-01 22:10:27,386 - ERROR - Error enabling SSP: Failed to enable SSP
Traceback (most recent call last):
  File "/root/Desktop/BlueDucky/BlueDucky.py", line 673, in <module>
    main()
  File "/root/Desktop/BlueDucky/BlueDucky.py", line 647, in main
    adapter.enable_ssp()
  File "/root/Desktop/BlueDucky/BlueDucky.py", line 111, in enable_ssp
    raise ConnectionFailureException("Failed to enable SSP")
ConnectionFailureException: Failed to enable SSP

``
**For the first time it run perfectly. When I try to run again it show error . 
I am using Kali Linux**

**Comment by Vuxorr** [comment]
change in scriot line from :

 ssp_command = ["sudo", "hciconfig", self.iface, "sspmode", "1"]

to

 ssp_command = ["sudo", "hciconfig", self.iface, "sspmode"]

without 1 at the end. I work for me.

**Comment by 6nsm** [comment]
[BlueDucky.txt](https://github.com/pentestfunctions/BlueDucky/files/15309986/BlueDucky.txt)
USE THIS COPY IT AND PASTE THIS TO YOUR ACTUAL BLUEDUCKY.PY

**Comment by Error13784** [comment]
> [BlueDucky.txt](https://github.com/pentestfunctions/BlueDucky/files/15309986/BlueDucky.txt) USE THIS COPY IT AND PASTE THIS TO YOUR ACTUAL BLUEDUCKY.PY

works! thank you!

**Comment by hadelbns** [comment]
thank u

**Comment by Ryzzen** [comment]
> change in scriot line from :
> 
> ssp_command = ["sudo", "hciconfig", self.iface, "sspmode", "1"]
> 
> to
> 
> ssp_command = ["sudo", "hciconfig", self.iface, "sspmode"]
> 
> without 1 at the end. I work for me.

This does not set the pairing mode, all it does is read the currently set mode.

Cf hciconfig source code:

```c
if (opt) {
		uint8_t mode = atoi(opt);

		if (hci_write_simple_pairing_mode(dd, mode, 2000) < 0) {
			fprintf(stderr, "Can't set Simple Pairing mode on hci%d: %s (%d)\n",
					hdev, strerror(errno), errno);
			exit(1);
		}
	} else {
		uint8_t mode;

		if (hci_read_simple_pairing_mode(dd, &mode, 1000) < 0) {
			fprintf(stderr, "Can't read Simple Pairing mode on hci%d: %s (%d)\n",
					hdev, strerror(errno), errno);
			exit(1);
		}
```

**Comment by jarvis8669** [comment]
hey i am using kali linux and i have same problem 
is there anybody can sortout it

**Comment by SuitedNerd** [comment]
we'll wifi or bluetooth attacks in a virtual machine like VirtualBox has problem's so you would need a secondairy laptop or a linux device which could actually perform attack's but sometime's its the adapter you are using which won't support packet injection when it comes to network adapters for example and for a example with bluetooth adapters it may not be really supported for attacking using BlueDucky or other software
